version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medods
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      
  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: referral-system
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./config:/app/config
      - ./db/migrations:/app/db/migrations
    command: ["dockerize", "-wait", "tcp://postgres:5432", "-timeout", "60s", "--", "/app/server", "-config=./config/config.yaml", "-migration=file://./db/migrations"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5